services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: connerklee-portfolio

    restart: unless-stopped

    ports:
      - "127.0.0.1:8081:80"

    read_only: true

    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /tmp

    security_opt:
      - no-new-privileges:true
